modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/MC-U-Team/Useful-Resources/issues"
displayURL="https://u-team.info/mods/usefulresources"
logoFile="logo.png"
license="Apache-2.0 License"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="usefulresources"
	version="${file.jarVersion}"
	displayName="Useful Resources"
	updateJSONURL="https://api.u-team.info/update/usefulresources.json"
	description="This mod adds many resources to the game and tries to unify them between mods."
	
	[[dependencies.usefulresources]]
	    modId="forge"
	    mandatory=true
	    versionRange="[35.0.7,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.usefulresources]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.16.4]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.usefulresources]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[3.1.4.173,)"
	    ordering="NONE"
	    side="BOTH"