modLoader="javafml"
loaderVersion="[27,)"
issueTrackerURL="https://github.com/MC-U-Team/Useful-Ores/issues"
displayURL="https://u-team.info/mods/usefulores"
logoFile="logo.png"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="usefulores"
	version="${file.jarVersion}"
	displayName="Useful Ores"
	updateJSONURL="https://api.u-team.info/update/usefulores.json"
	description="This mod adds many ores to the game and tries to unify them between mods."
	
	[[dependencies.usefulores]]
	    modId="forge"
	    mandatory=true
	    versionRange="[27.0.13,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.usefulores]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.3]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.usefulores]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[2.5.5.117,)"
	    ordering="NONE"
	    side="BOTH"