modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/MC-U-Team/Useful-Resources/issues"
displayURL="https://u-team.info/mods/usefulresources"
logoFile="logo.png"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="usefulresources"
	version="${file.jarVersion}"
	displayName="Useful Resources"
	updateJSONURL="https://api.u-team.info/update/usefulresources.json"
	description="This mod adds many resources to the game and tries to unify them between mods."
	
	[[dependencies.usefulresources]]
	    modId="forge"
	    mandatory=true
	    versionRange="[28.0.27,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.usefulresources]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.4]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.usefulresources]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[2.7.0.129,)"
	    ordering="NONE"
	    side="BOTH"